services:
  ledger:
    depends_on:
      database:
        condition: service_healthy
    build:
      dockerfile: "Dockerfile"
      target: "ledger"
    env_file:
      - ".env"
    volumes:
      - "./apps/backend/:/app/backend/:r"
      - "./shared/:/app/shared"
    expose:
      - ${APP_PORT}
    networks:
      local:
    command:
      - "backend.main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8082"
      - "--reload"
  auth:
    depends_on:
      database:
        condition: service_healthy
    build:
      dockerfile: "Dockerfile"
      target: "ledger"
    env_file:
      - ".env"
    volumes:
      - "./apps/auth/:/app/auth/:r"
      - "./shared:/app/shared"
    expose:
      - 8081
    networks:
      local:
    command:
      - "auth.main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8081"
      - "--reload"
  frontinstaller:
    build:
      dockerfile: "Dockerfile"
      target: "reactapp"
    volumes:
      - "./apps/frontend/:/app:rw"
    networks:
      local:
    command: [ "i" ]
  front:
    depends_on:
      frontinstaller:
        condition: service_completed_successfully
    build:
      dockerfile: "Dockerfile"
      target: "reactapp"
    environment:
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
      - PORT=${ADMIN_FRONT_PORT}
      - REACT_ROUTING_MAIN_SITE=/
    volumes:
      - "./apps/frontend/:/app:r"
    expose:
      - ${ADMIN_FRONT_PORT}
    ports:
      - "${ADMIN_FRONT_PORT}:${ADMIN_FRONT_PORT}"
    networks:
      local:
    command: [ "start" ]
  database:
    build:
      dockerfile: "Dockerfile"
      target: "database"
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      MARIADB_USER: "${DB_USER}"
      MARIADB_PASSWORD: "${DB_PASS}"
      MARIADB_DATABASE: "${DB_NAME}"
      MARIADB_ROOT_PASSWORD: "${DB_PASS}"
    expose:
      - 3306
    volumes:
      - "./config/database/dev-ver/:/docker-entrypoint-initdb.d:ro"
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 30s
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      local:
  dbadmin:
    depends_on:
      database:
        condition: service_healthy
    build:
      dockerfile: "Dockerfile"
      target: "dbadmin"
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASS}
    ports:
      - "${ADMINER_PORT}:80"
    networks:
      local:
  reverseproxy:
    depends_on:
      database:
        condition: service_healthy
    build:
      dockerfile: "Dockerfile"
      target: "reverseproxy"
    env_file:
      - ".env"
    restart: unless-stopped
    volumes:
      - "./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./config/nginx/mime.types:/etc/nginx/mime.types:ro"
    networks:
      local:
    ports:
      - "${APP_PORT}:80"

networks:
  local:
