name: ESLint Check

on:
  pull_request:
  push:
    branches: [main]

jobs:
  eslint:
    runs-on: ubuntu-latest
    name: "Check JavaScript code with ESLint"
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd apps/front-admin
          npm install

      - name: Run ESLint
        run: |
          cd apps/front-admin
          npm run lint
